### PR TITLE
Made "larry" and "people" seperate categories.

### PR DESCRIPTION
**Pull request by donvi-bz**
I took "Larry" out of the `people` category and put it in its own category. This way we control which spaces in a `drama` the name "Larry" goes into. Before it was random, meaning there was the possibility of having no "Larry" at all, or too many "Larry"s to make a valid sentence. Now we will always have a set number of "Larry"s getting put in each drama, AND we will never have too many "Larry"s in a sentence!

If you like this idea, then pull! Otherwise I'll try and fix the too many/ too few Larry issue another way.

### CODE REVIEW

**Comment by ParadauxIO** [comment]
Putting yourself in is very cheeky 
But I approve !

**Review by ParadauxIO — APPROVED** [review]
Looks good to me!

**Comment by ocelotpotpie** [comment]
I like this idea from a functional point of view.

However - @donvi-bz it is indeed a bit cheeky to add yourself.

I think either pull your name from the people list, add some other known regulars, or make that part of a second PR for review.

Otherwise looks good!

**Review by ocelotpotpie — APPROVED** [review]
Solid work!

**Review by ParadauxIO — APPROVED** [review]
Appreciate the additional commit

**Pull request merged**
